---
 
- hosts: all
  become: true
  tasks:
 
  - name: install updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
 
- hosts: server
  become: true
  tasks:
 
  - name: install apache and php for Ubuntu servers
    tags: apache
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"
 
- hosts: nodes
  become: true
  tasks:


  - name: install vim-nox
    tags: vim
    apt:
      name: vim-nox
      state: latest
    when: ansible_distribution == "Ubuntu"
