---
 
- hosts: all
  become: true
  tasks:
 
  - name: clean cache
    apt:
      autoremove: yes

  - name: Run the equivalent of "apt-get update" as a separate step
    apt:
      update_cache: yes

  - name: Update all packages to the latest version
    apt:
      upgrade: dist
